### ISSUE TITLE
Amazon SES?

### ISSUE THREAD

**Issue by CodeMeZone** [garrrikkotua/morningly#4]
Never really played with Django, so something new for me to learn. 

How would I get Amazon SES to work with this and not MAILGUN (overpriced imo)

Thanks!

https://anymail.dev/en/stable/esps/amazon_ses/

**Comment by jarrodlatshaw** [comment]
You should be able to use anymail as you indicated. You should be able to modify it in settings and follow the general instructions in the link you sent. I was going to use send grid and decided against it in the end.

**Comment by CodeMeZone** [comment]
> You should be able to use anymail as you indicated. You should be able to modify it in settings and follow the general instructions in the link you sent. I was going to use send grid and decided against it in the end.

Alright, thanks! I haven't gotten into this at all but it seems like a small project.

**Comment by garrrikkotua** [comment]
@CodeMeZone it is possible, but requires installing additional library. It would probably involve changing settings.py, unfortunately I think it is quite hard to support all this options through .env

But thanks for looking into the project! I'm working on docker version - takes time because I am not a big expert with it

**Comment by CodeMeZone** [comment]
@garrrikkotua I guess we're both trying something new lol!

Hmm.. I guess it's something that I'll try my best at.
